### ISSUE TITLE
Overview # of registered persons

### ISSUE THREAD

**Issue by jefking** [Missing-Children-Society-Canada/authorization#11]
We are not able to display the PII of persons who have registered; however, we should be able to display the total number of persons that have signed up so that we can understand if the platform is growing etc.

**Comment by vatdaell** [comment]
Just want to confirm that the persons are social media accounts or individual people

**Comment by jefking** [comment]
@vatdaell that is a good idea. We could surface:
X number of Users
and X number of social media accounts

**Comment by vatdaell** [comment]
Hey @jefking can you please check my pull request #14  and please let me know if I need to change anything

**Comment by jefking** [comment]
@vatdaell I was reviewing this; and I made a mistake. This needs to be in the Portal-Node project as that is where the administrators log in; this site is strictly for end user sign up.
Thanks for your work, but I am going to close the PR as well.
It is entirely my fault as I opened this ticket in the wrong project.

**Comment by vatdaell** [comment]
@jefking no worries I'll look into Portal-Node then
