### ISSUE TITLE
Mobile Apps

### ISSUE THREAD

**Issue by vatdaell** [Missing-Children-Society-Canada/authorization#8]
I know this isn't the best place to ask this but I was wondering if there is a mobile app for this project in the future?

**Comment by WirelessLife** [comment]
@vatdaell we actually created a Xamarin app for iOS and Android to provide Police instant notification of #HFM being detected.  The problem is that Police cannot receive information immediately and without case # assignment due to current laws.  I'd be interested in your ideas though.

**Comment by vatdaell** [comment]
@WirelessLife Ah I see, yeah the app will be limited but I was thinking of having some sort of public facing app that alerts people of missing children in the area but I feel it will be exactly like amber alert but with more social sharing features in order to spread the message.

**Comment by WirelessLife** [comment]
Already created @vatdaell and running on Azure.  You can register here: https://mcsc.ca/search-program/most-valuable-network/

**Comment by vatdaell** [comment]
@WirelessLife that makes more sense to use. Yeah I can see why a public facing app will be less useful.
